### ISSUE TITLE
Storing user data securely on s3

### ISSUE THREAD

**Issue by pbywater** [pbywater/echo#116]
Option 1
https://aws.amazon.com/sdk-for-node-js/
http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/s3-examples.html
IAM users - http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/iam-examples-managing-users.html

**Comment by pbywater** [comment]
Option 2:
Okta/Stormpath tutorial: https://stormpath.com/blog/securely-storing-files-node-s3

Looks like the node module hasn't been used much so this may be a bad option

**Comment by pbywater** [comment]
@des-des - is option 1 the kind of thing we need to be doing?

**Comment by des-des** [comment]
Option one is the node sdk. That is not an option, it is the module you will need to use with any solution that you go with.

I think we should use signedUrls.

Here is a kind of general example: https://github.com/stackery/s3-signed-urls-example/blob/master/Stackery/functions/API%20Handler/index.js

Want want something like that, but with an auth layer and some db interateration.

**Comment by des-des** [comment]
I think if you all have a think about this you might get somewhere.

A signedUrl a url, that has certain permissions and a timeout built into it. (you could think about it as a url with a JWT inside it, if that is helpful).

You will create signed urls that allow access, and write permissions for a single interaction.

When a user wants to create a resource the flow would be

  1. User makes request to server (I want to save a photo please!).
  2. Server authenticates the user
  3. Server generates a url that allows user to create a particular resource (with a key specified by your server)
  4. Server stores name of resource in db
  5. server responds to user with signedUrl
  6. user posts resource to s3

**Comment by des-des** [comment]
https://github.com/berkeley-homes/near-miss-positive-intervention/blob/master/src/server/model/image.js
