### ISSUE TITLE
Choose colour palette and font

### ISSUE THREAD

**Issue by pbywater** [pbywater/echo#2]

**Comment by ghost** [comment]
We need to choose a colour palette that covers the following points:
1. Primary colour
2. Secondary colour
3. Accent colour
4. Error colour
5. Success colour.

**Comment by pbywater** [comment]
Provisional palette: https://coolors.co/8ea5ce-91cfcf-fdacab-ff3f56-3993dd

@nogainbar

**Comment by pbywater** [comment]
Font ideas:
https://www.download-free-fonts.com/details/96003/proxima-nova

Or maybe:
https://fonts.google.com/specimen/Quicksand?selection.family=Quicksand
http://font2s.com/fonts/50876/circular_std_bold.html#.WVEjbBPytN0
https://fonts.google.com/specimen/Work+Sans
