### ISSUE TITLE
Set up basic d3

### ISSUE THREAD

**Issue by pbywater** [pbywater/echo#3]
(visually similar to before)

**Comment by ghost** [comment]
We need to get together a clean, well-ordered basic layout of the d3 that we will be working with. 
As a reminder, [here's](http://blockbuilder.org/jalapic/cf1454d62c7efa48d96ee4d803856dfa) the original piece that inspired us.

**Comment by ghost** [comment]
We need to: 
- [x] set up index.html file and import d3
- [x] add an empty div, give it a class
- [x] create a margins.js file that appends an svg to this div, and also sets out the margins of the container

After this we can then start building the main d3 file.
