### ISSUE TITLE
Decide on schema

### ISSUE THREAD

**Issue by pbywater** [pbywater/echo#4]
(normalisation)

**Comment by ghost** [comment]
Potenital schema for memories:

| Column      | Type                  | Modifiers        |
|:----------------:|:-------------:|:------------:|
| id          | integer               | not null default |
| user_id          | integer               | not null |
| likes       | integer               |                  |
| rating      | integer               |                  |
| visits      | integer               |                  |
| memory | varchar(300) | not null         |

memory refers to the url to where the image/video etc is stored on s3
visits refers to how many times the user has visited
the user_id will be taken from the users table (outlined below) and accessed via an inner join.

**Comment by ghost** [comment]
Potential schema for users:

| Column   | Type         | Modifiers        |
|:----------------:|:-------------:|:------------:|
| id       | integer      | not null default |
| username | varchar(50)  | not null         |
| password | varchar(50)  | not null         |
| email    | varchar(200) | not null         |

**Comment by ghost** [comment]
Potential schema for media types:

| Column      | Type                  | Modifiers        |
|:----------------:|:-------------:|:------------:|
| text         | array               |                   |
| audio       | array               |                  |
| video      | array               |                  |
| image      | array               |                  |

The arrays would contain a list of ids, referencing the memories that have that particular media type. 

e.g. if memories 6, 7, and 19 are all videos, then the video array in this table will be: [6, 7, 19]

**Comment by ghost** [comment]
There was also talk of storing tags in a database to review their use across the userbase for AF to analyse. We need to create a schema for this one the details are ironed out.

**Comment by ghost** [comment]
I think we should keep this unclosed until all the schemas have been finalised (see the comment above)
