### ISSUE TITLE
Bouncey bouncey effect on nodes

### ISSUE THREAD

**Issue by pbywater** [pbywater/echo#51]

**Comment by ghost** [comment]
Links we should use to help:
- [1 movement](http://blockbuilder.org/kenpenn/268878b410ddb1201277be3f0305d566)
- [2 adding a node](http://blockbuilder.org/davo/c2679892f54b8155d9b3)
- [3 For collision](http://blockbuilder.org/Thanaporn-sk/20eb310ab0c26f18a6968c157e4d0927)
