### ISSUE TITLE
Add dummy JSON data 

### ISSUE THREAD

**Issue by pbywater** [pbywater/echo#6]
(to implement algorithm)

**Comment by ghost** [comment]
Note: in my experience working with d3 v4, I've not been able to connect directly to a JSON file on chrome  – instead I've hosted the JSON on gist and connected via the url. Will be worth researching.

**Comment by ghost** [comment]
[here's](https://gist.github.com/ConchobarMacNessa/8d852e941cf9c86c98b4b22a269f462e#file-echotestdata-json) the link to the temporary gist with our dummy data
