### ISSUE TITLE
Integrate update pattern

### ISSUE THREAD

**Issue by pbywater** [pbywater/echo#69]
Functions to update links and nodes that can be called when we add or delete a node.

**Comment by ghost** [comment]
http://blockbuilder.org/davo/c2679892f54b8155d9b3

**Comment by ghost** [comment]
https://bl.ocks.org/mbostock/3808234

**Comment by ghost** [comment]
This might help : https://stackoverflow.com/questions/38834666/d3-v4-update-merge-grouped-data

**Comment by ghost** [comment]
https://stackoverflow.com/questions/38011393/recreating-collapsible-force-layout-using-d3-v4
** https://stackoverflow.com/questions/41625978/d3-v4-update-pattern-for-groups
