### ISSUE TITLE
Set up S3

### ISSUE THREAD

**Issue by pbywater** [pbywater/echo#9]

**Comment by joeylouise** [comment]
Hey @amgoforth, we're just looking into S3 for storage and wondering if Anna Freud already has an account set up with AWS ([Amazon Web Services](https://aws.amazon.com/)) or if we should look into setting something up?

**Comment by joeylouise** [comment]
Email from Alex:

Hi,
I don’t think AFC has one,  Mark was using it, but he left AFC yesterday.  I’ve emailed his personal address, but he’s moving house today and this w/e so it might be a few days before we hear back, which means it might be easier to create one yourselves, depending on how long that will take.
 
All the best
 
Alex

**Comment by joeylouise** [comment]
See #116 for info relating to s3
